service: drupal-mrn

provider:
    name: aws
    region: us-east-1
    runtime: provided.al2
    stage: prod
    versionFunctions: false
    httpApi:
        cors: true

plugins:
    - ./vendor/bref/bref

functions:
    changelog:
        handler: changelog.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-81-fpm}
        events:
          - httpApi:
              method: 'GET'
              path: /changelog
    project:
        handler: project.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-82-fpm}
        events:
          - httpApi:
              method: 'GET'
              path: /project

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
